### ISSUE TITLE
pgenthreader.sh (psipred: command not found)

### ISSUE THREAD

**Issue by shalinikaushik** [psipred/psipred#1]
I am trying to run pgenthreader.sh script, the result is :

Finished 3 iterations PSI-BLAST usage : psipred weight-file seq-file usage : psipass2 weight-file seq-file DCA DCB PSIPRED failed ... exiting early (It is creating the sequence.pgen.ss file but its blank)

so, I tried to run psipred command separately : /media/kakarot/ppi/psipred/bin$ psipred /media/kakarot/ppi/genthreader/sequence.iter3.mtx /media/kakarot/ppi/psipred/data/weights.dat /media/kakarot/ppi/psipred/data/weights.dat2 /media/kakarot/ppi/psipred/data/weights.dat3 > /media/kakarot/ppi/genthreader/sequence.pgen.ss

But i am getting : psipred: command not found

**Comment by DanBuchan** [comment]
I believe this error was an installation issue and was solved via email
