### ISSUE TITLE
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048

### ISSUE THREAD

**Issue by li0604** [psipred/psipred#10]
Dear professor,

When I run my data with runpsipred, it gave me an error "[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048". I have try my best to solve this problem, but it did not work.

Before I run the really input file and reference database. I have test the example data with a built data of  several sequences. I got the right output file.

The really database I need contining 86007 sequence. and the input file containing 6048 sequences. Details showing as follwing:

#formatting the database
formatdb -i all_seq_sp6048_cluster.faa -n all_seq -t all_seq -p T

#the formatdb.log 

========================[ Nov 26, 2021  8:39 AM ]========================
Version 2.2.26 [Sep-21-2011]
Started database file "all_seq_sp6048_cluster.faa"
Formatted 86007 sequences in volume 0
SUCCESS: formatted database all_seq_db

# reedited runpsipred (just changing two lines)

# The name of the BLAST data bank
#set dbname = uniref90
#set dbname = test_db 
set dbname = all_seq

# Where the NCBI programs have been installed
#set ncbidir = /usr/local/bin
set ncbidir = /data/liqingmei/tools/psipred/blast-2.2.26/bin

#the error 
#tail -n 5 psitmp2049390c0c660c.blast
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048

#####################

This analysis is very important for me, would you help me to solve this problem?

Thanks a lot.

**Comment by DanBuchan** [comment]
Closing as this is the same as https://github.com/psipred/psipred/issues/11
