### ISSUE TITLE
ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048

### ISSUE THREAD

**Issue by li0604** [psipred/psipred#11]
Dear professor,

When I run my data with runpsipred, it gave me an error "[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048". I have try my best to solve this problem, but it did not work.

Before I run the really input file and reference database. I have test the example data with a built data of  several sequences. I got the right output file.

The really database I need contining 86007 sequence. and the input file containing 6048 sequences. Details showing as follwing:

#formatting the database
formatdb -i all_seq_sp6048_cluster.faa -n all_seq -t all_seq -p T

#the formatdb.log 

========================[ Nov 26, 2021  8:39 AM ]========================
Version 2.2.26 [Sep-21-2011]
Started database file "all_seq_sp6048_cluster.faa"
Formatted 86007 sequences in volume 0
SUCCESS: formatted database all_seq_db

# reedited runpsipred (just changing two lines)

# The name of the BLAST data bank
#set dbname = uniref90
#set dbname = test_db 
set dbname = all_seq

# Where the NCBI programs have been installed
#set ncbidir = /usr/local/bin
set ncbidir = /data/liqingmei/tools/psipred/blast-2.2.26/bin

#the error 
#tail -n 5 psitmp2049390c0c660c.blast
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048
[blastpgp] ERROR: ncbiapi [000.000]  ObjMgrNextAvailEntityID failed with idx 2048

#####################

This analysis is very important for me, would you help me to solve this problem?

Thanks a lot.

**Comment by DanBuchan** [comment]
It's not very clear what you're trying to do here. Before configuring PSIPRED can you get legacy_blast to work on the commandline?

I also do not understand what you mean by

```
The really database I need contining 86007 sequence. and the input file containing 6048 sequences. 
```

We would advise that the sequence database for PSIPRED is either the genbank's nr90 or Uniprot90. We use Uniprot90 and would advise you use that. If you replace the search database with a smaller one of 86007 then the psipred output will likely be much less accurate. PSIPRED can not run with an input file with multiple sequences. Input files should have a single sequence. Typically you might write a small script that extract each sequence from your input set and runs it one at a time.

**Comment by li0604** [comment]
Thanks for your help. I want to build a special database according to my analysis. I will split the input file and run only one sequence at a time.

**Comment by li0604** [comment]
Dear profesoor,
Thanks for your help. I will try again follwing your suggestion. 
I am sorry to upload the question twice.It may be the poor  web. I refreshed the page.


Best wishes,
Qingmei












At 2021-11-27 02:01:52, "Daniel" ***@***.***> wrote:

It's not very clear what you're trying to do here. Before configuring PSIPRED can you get legacy_blast to work on the commandline?

I also do not understand what you mean by

The really database I need contining 86007 sequence. and the input file containing 6048 sequences. 


We would advise that the sequence database for PSIPRED is either the genbank's nr90 or Uniprot90. We use Uniprot90 and would advise you use that. If you replace the search database with a smaller one of 86007 then the psipred output will likely be much less accurate. PSIPRED can not run with an input file with multiple sequences. Input files should have a single sequence. Typically you might write a small script that extract each sequence from your input set and runs it one at a time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by li0604** [comment]
Sorry, I still want to know if I build a database of my own protein or peptide sequences that many of them with unknown function and I dot know if they have 2D or 3D structure is performable.

**Comment by DanBuchan** [comment]
I'm still not clear what you are trying to achieve with PSIPRED. I don't understand what this dataset of 86007 protein sequences is and why you want to use it. Could explain what this is and why you think you need to use it?

If you want to accurately predict the secondary structure of 6,048 input protein sequences you should set up and install PSIPRED to use legacy_blast the uniprot90. It is essential for psipred that the search database be as large as possible to ensure sufficient evolutionary information about each input sequence can be found.

**Comment by li0604** [comment]
Dear professor,
Thanks for your e-mail. I want to know the second structure of the proteins I am focusing. The number is very large, so I want to performe with  command.
I have changed to use the uniref90 database. It works without the any error.
Thank you very much.


Best wishes,
QIngmei Li













At 2021-11-29 19:34:04, "Daniel" ***@***.***> wrote:

I'm still not clear what you are trying to achieve with PSIPRED. I don't understand what this dataset of 86007 protein sequences is and why you want to use it. Could explain what this is and why you think you need to use it?

If you want to accurately predict the secondary structure of 6,048 input protein sequences you should set up and install PSIPRED to use legacy_blast the uniprot90. It is essential for psipred that the search database be as large as possible to ensure sufficient evolutionary information about each input sequence can be found.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DanBuchan** [comment]
I'm glad this is working now. I'll close this issue
