### ISSUE TITLE
How to visualize locally generated results?

### ISSUE THREAD

**Issue by Khainhienluu** [psipred/psipred#13]
I installed Psipred on my computer (linux) to analyze a sequence >1500 residues. How can I visualize the results like the web server? I have all 3 .horiz, .ss, and .ss2 files.

**Comment by DanBuchan** [comment]
The visualisation code for the webserver is made up of specific javascript plugins embedded in our webpage. We don't have standalone versions of those visualisations.

Typically we'd recommend using something like Jalview (https://www.jalview.org/) or ESPript (https://espript.ibcp.fr/ESPript/ESPript/). You can input your sequence plus a file of annotations. You can derive the annotation input file from coordinates from the .ss2 files

**Comment by Khainhienluu** [comment]
Thank you!
