### ISSUE TITLE
Ncbi BLAST, nr database

### ISSUE THREAD

**Issue by shalinikaushik** [psipred/psipred#2]
I am running the command for BLAST : blastp -query /Users/shalini/Desktop/shalini/project/unmodelled_fasta/AAA18895.fasta -outfmt "7 sacc qcovs pident ppos evalue" -db=/Users/shalini/Downloads/nr -out=/Users/shalini/Desktop/shalini/project/blast_resultnr

After running for one and half hour, it results in Error memory mapping:/Users/shalini/Downloads/nr.79.phr openedFilesCount=251 threadID=0 BLAST Database error: Cannot memory map /Users/shalini/Downloads/nr.79.phr. Number of files opened: 251

I am working on macOS. also I have built the database of nr which results in 114 .phr, .pin, .psq and .pog files.

Please help me, if anyone knows.

**Comment by DanBuchan** [comment]
This looks like an issue running blastp. You should approach the BLAST developers for help with their software.
