### ISSUE TITLE
psipred error

### ISSUE THREAD

**Issue by shalinikaushik** [psipred/psipred#3]
i ran a psipred command of pgenthreade.sh script
`tcsh psipred /media/kakarot/ppi/genthreader/sequence.iter3.mtx /media/kakarot/ppi/psipred/data/weights.dat /media/kakarot/ppi/psipred/data/weights.dat2 /media/kakarot/ppi/psipred/data/weights.dat3 > /media/kakarot/ppi/genthreader/sequence.pgen.ss`

it results in

`Unmatched '`'.`

anyone please can help

**Comment by DanBuchan** [comment]
I believe this was an installation error and that we resolved this via email
