### ISSUE TITLE
docker image and code license

### ISSUE THREAD

**Issue by eliza-m** [psipred/psipred#4]
I was wondering if there exists a public docker image of PsiPred or if the code license allows generating a docker image and uploading it on a public registry such as quay.io or docker hub ?

Thank you !
Eliza

**Comment by DanBuchan** [comment]
Hi,

We don't provide any deployment automation things for the psipred software packages. We have been toying with writing installers for all our software packages but that probably won't be docker based (and I can't tell you when that will get done).

You're welcome to make a docker image for psipred and distributing said image to a public, non-profit registry should be allowed within the terms of the licence. If you do go ahead with this we would gladly add the dockerfile to the repo so please do send us a pull-request if you're happy to.
