### ISSUE TITLE
Position Specific Scoring Matrix (PSSM)

### ISSUE THREAD

**Issue by SaidaSaad** [psipred/psipred#5]
Thank you for sharing that.
I would like to know if you have source code for calculating PSSM for any data set of sequences.
In fact I have my own data set (Single sequences)  I need to  know how to calculate PSSM . 
And if there is any source code for that.

Thanks

**Comment by DanBuchan** [comment]
The PSSM is calculated by the code provided by the NCBI's blast. 

We use the makemat exe provided by legacy blast to convert a legacy blast checkpoint file to the PSSM. 

I know that the blast source code is online but you might need to contact the BLAST developers to be pointed in the right direction

**Comment by SaidaSaad** [comment]
Thank you very much 
Do you have any infor about if PSSM can be calculated for single  sequence protein or it should be for multiple align sequences ?

**Comment by DanBuchan** [comment]
You could calculate a PSSM for a single sequencce but it will in essence be a binary matrix/one-hot-value matrix as you only see a single residue at any given position on the sequence (alignment). It's not an especially informative calculation.
