### ISSUE TITLE
psipred.chk not found?!

### ISSUE THREAD

**Issue by biotech70** [psipred/psipred#7]
Hi. When I try to run Psipred, I get the following error:
![Untitled](https://user-images.githubusercontent.com/73783725/118172396-8f996200-b441-11eb-8a44-95064288e4bc.png)

**Comment by DanBuchan** [comment]
You are probably running the wrong blast. PSIPRED requires LEGACY BLAST

Also, what is run_psipred.pl? We can't offer any support or guidance for code that we didn't write.

**Comment by DanBuchan** [comment]
Closing as discussion has moved back to the original thread
