### ISSUE TITLE
How to use psipred with multiple fasta seq in a file

### ISSUE THREAD

**Issue by sekhwal** [psipred/psipred#9]
Hi,
I have a fasta file containing more than 1000 sequencing. I am looking to predict secondary structure prediction of these sequences to see the structure of the motif in these sequences. Please suggest if I can use psipred in this regards.

**Comment by DanBuchan** [comment]
For either the server or the standalone software you need to split each sequence out in to its own file and run each file one at a time. PSIPRED has no batch prediction abilities
